title: Ben Tan Kiang Thong
logo: assets/img/Circular Profile pic 2023.png
description: >
  Hi there, I'm Ben.
  <br><br>
  An engineer, scientist and project manager all in one. 
  <br><br>
  With a passion in leveraging data to make drive insights and solve complex problems, I am diving deep into the world of data science.
show_downloads: true
theme: jekyll-theme-minimal
