title: Ben Tan Kiang Thong
logo: assets/img/Circular Profile pic 2023.png
description: >
  Hi there, I'm Ben.
  <br><br>
  An engineer, scientist and project manager all in one. 
  <br><br>
  With a passion in leveraging data to draw insights and solve complex problems, I help corporates and individuals make informed decisions.
show_downloads: true
theme: jekyll-theme-minimal
